In [8]:
import numpy as np

a = np.arange(1, 20, 2)
print(a)

print('='*20)
b = np.linspace(0, 100, 5)
print(b)
print(b.dtype)
print('='*20)
b = np.linspace(0, 100, 5 , dtype=int)
print(b)
print(b.dtype)

print('='*20)

char_arr = np.array(['hahaha :)'])
print(char_arr)
print(char_arr.dtype)

print('='*20)
one_dim_arr = np.array([1,2,3,4,5,6])
print(one_dim_arr)
print('='*10)
two_dim_arr = np.reshape(one_dim_arr, (2,3))
print(two_dim_arr)
print('='*10)
three_dim_arr = np.reshape(one_dim_arr, (1,1,6))
print(three_dim_arr)

print('='*20)
print(three_dim_arr.ndim)
print(three_dim_arr.size)
print(two_dim_arr.size)
print(three_dim_arr.shape)

[ 1  3  5  7  9 11 13 15 17 19]
[  0.  25.  50.  75. 100.]
float64
[  0  25  50  75 100]
int64
['hahaha :)']
<U9
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 2 3 4 5 6]]]
3
6
6
(1, 1, 6)
